@extends('layouts.app')
@section('content')
@php
    $cardStyles=['Total Content'=>['#edf4ff','#1769ff','▤'],'In Production'=>['#fff2e8','#f97316','⚙'],'Review'=>['#f2edff','#7c4dff','◉'],'Scheduled'=>['#e8f8f9','#089eaa','□'],'Published'=>['#eaf7ed','#32a852','✓']];
    $statusSlugs=['In Production'=>'in_production','Review'=>'review','Scheduled'=>'scheduled','Published'=>'published'];
    $maxPillar=max(1,(int)$byPillar->max('total')); $maxPlatform=max(1,(int)$byPlatform->max('contents_count'));
@endphp
<div class="mb-6"><h1 class="page-title">Dashboard <span class="text-2xl">👋</span></h1><p class="page-subtitle">Good {{ now()->hour < 12 ? 'morning' : (now()->hour < 18 ? 'afternoon' : 'evening') }}, {{ explode(' ',auth()->user()->name)[0] }}! Here’s what’s happening with your content.</p></div>
<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">
@foreach($stats as $label=>$value)@php([$bg,$color,$icon]=$cardStyles[$label]??['#edf4ff','#1769ff','•'])<article class="panel flex min-h-[114px] items-start gap-4 p-4"><span class="soft-icon shrink-0" style="background:{{ $bg }};color:{{ $color }}">{{ $icon }}</span><div><div class="text-xs font-semibold text-[#334563]">{{ $label==='Review'?'Needs Review':$label }}</div><div class="mt-1 text-[28px] font-bold leading-none tracking-tight">{{ $value }}</div><div class="mt-3 text-[10px]" style="color:{{ $color }}">{{ $label==='Total Content'?'All active records':($stats['Total Content']?round($value/$stats['Total Content']*100).'% of total content':'No content yet') }}</div></div></article>@endforeach
</div>
<div class="mt-5 grid gap-5 xl:grid-cols-12">
<section class="panel xl:col-span-4"><div class="panel-header"><div><h2 class="section-title">Production Overview</h2><p class="mt-1 text-[10px] text-slate-500">Current content status distribution.</p></div><span class="soft-icon">◎</span></div><div class="space-y-5 p-5">@foreach($statusSlugs as $label=>$slug)@php($count=$stats[$label]??0)<div class="grid grid-cols-[100px_1fr_30px_42px] items-center gap-3 text-xs"><span>{{ $label }}</span><span class="h-1.5 overflow-hidden rounded-full bg-slate-100"><i class="block h-full rounded-full bg-blue-500" style="width:{{ $stats['Total Content']?round($count/$stats['Total Content']*100):0 }}%"></i></span><b class="text-right">{{ $count }}</b><span class="text-right text-slate-500">{{ $stats['Total Content']?round($count/$stats['Total Content']*100):0 }}%</span></div>@endforeach</div><a href="{{ route('production') }}" class="mx-5 mb-5 inline-flex text-xs font-semibold text-blue-600">View Production Board →</a></section>
<section class="panel xl:col-span-4"><div class="panel-header"><h2 class="section-title">Upcoming Deadlines</h2><a href="{{ route('calendar') }}" class="text-[11px] font-semibold text-blue-600">View Calendar →</a></div><div class="divide-y divide-slate-100 px-5">@forelse($upcoming->take(5) as $c)<a href="{{ route('content.show',$c) }}" class="flex items-center gap-3 py-3.5"><span class="grid h-10 w-10 shrink-0 place-items-center rounded-lg border border-slate-200 text-center text-[10px] font-bold text-blue-600">{{ $c->publish_date->format('M') }}<b class="block text-sm leading-none text-slate-800">{{ $c->publish_date->format('d') }}</b></span><span class="min-w-0 flex-1"><b class="block truncate text-xs">{{ $c->title }}</b><small class="text-[10px] text-slate-500">{{ $c->pic?->name }}</small></span><span class="badge status-{{ $c->status->value }}">{{ $c->status->label() }}</span></a>@empty<p class="py-8 text-center text-xs text-slate-400">No upcoming deadlines.</p>@endforelse</div></section>
<section class="panel xl:col-span-4"><div class="panel-header"><div><h2 class="section-title">Today & Next Up</h2><p class="mt-1 text-[10px] text-slate-500">Content scheduled for today.</p></div><span class="soft-icon">▣</span></div><div class="divide-y divide-slate-100 px-5">@forelse($today->take(4) as $c)<a href="{{ route('content.show',$c) }}" class="flex items-center gap-3 py-4"><span class="grid h-11 w-11 shrink-0 place-items-center rounded-lg bg-gradient-to-br from-blue-100 to-indigo-100 text-blue-600">▶</span><span class="min-w-0 flex-1"><small class="text-[10px] text-slate-500">{{ $c->platforms->pluck('name')->join(' · ') }}</small><b class="mt-1 block truncate text-xs">{{ $c->title }}</b><small class="text-[10px] text-slate-500">{{ $c->pic?->name }}</small></span><span class="badge status-{{ $c->status->value }}">{{ $c->status->label() }}</span></a>@empty<p class="py-8 text-center text-xs text-slate-400">No content scheduled today.</p>@endforelse</div></section>
</div>
<div class="mt-5 grid gap-5 lg:grid-cols-2">
<section class="panel p-5"><div class="mb-5 flex items-center gap-3"><span class="soft-icon">◔</span><h2 class="section-title">Content by Pillar</h2></div><div class="space-y-4">@foreach($byPillar as $x)<div class="grid grid-cols-[140px_1fr_28px] items-center gap-3 text-xs"><span class="truncate">{{ $x->pillar?->name }}</span><span class="h-2 overflow-hidden rounded-full bg-slate-100"><i class="block h-full rounded-full bg-blue-500" style="width:{{ round($x->total/$maxPillar*100) }}%"></i></span><b class="text-right">{{ $x->total }}</b></div>@endforeach</div><p class="mt-5 text-[10px] text-slate-500">{{ $stats['Total Content'] }} contents total</p></section>
<section class="panel p-5"><div class="mb-5 flex items-center gap-3"><span class="soft-icon">▱</span><h2 class="section-title">Content by Platform</h2></div><div class="space-y-4">@foreach($byPlatform as $x)<div class="grid grid-cols-[100px_1fr_28px] items-center gap-3 text-xs"><span>{{ $x->name }}</span><span class="h-2 overflow-hidden rounded-full bg-slate-100"><i class="block h-full rounded-full bg-blue-500" style="width:{{ round($x->contents_count/$maxPlatform*100) }}%"></i></span><b class="text-right">{{ $x->contents_count }}</b></div>@endforeach</div><p class="mt-5 text-[10px] text-slate-500">Live distribution across channels</p></section>
</div>
@endsection
