@extends('layouts.app')
@section('content')
@php($seriesData=$pillars->flatMap(fn($p)=>$p->series->map(fn($s)=>['id'=>$s->id,'name'=>$s->name,'pillar_id'=>$p->id]))->values())
<div x-data="{open:false,pillar:'',series:@js($seriesData),filterSeries(){return this.series.filter(x=>String(x.pillar_id)===String(this.pillar))}}">
 <div class="flex justify-between mb-5"><div><h1 class="text-2xl font-bold">Ideas</h1><p class="text-xs text-slate-500">Tempat ide sebelum masuk Content Plan</p></div><div class="flex gap-2">@can('ideas.bulk_import')<a href="{{ route('ideas.template') }}" class="btn border">Download Excel Template</a><button data-testid="bulk-ideas" @click="$refs.bulk.showModal()" class="btn border">Bulk Upload Ideas</button>@endcan @can('ideas.create')<button data-testid="add-idea" @click="open=true" class="btn btn-blue">+ Add Idea</button>@endcan</div></div>
 <div class="panel overflow-x-auto"><table class="table w-full"><thead><tr><th>Idea</th><th>Pillar</th><th>Series</th><th>Format</th><th>Submitted By</th><th>Department</th><th>Status</th><th>Created</th><th>Action</th></tr></thead><tbody>
 @foreach($ideas as $idea)<tr data-testid="idea-row"><td class="font-semibold max-w-xs prose prose-sm">{!! $idea->idea !!}</td><td>{{ $idea->pillar->name }}</td><td>{{ $idea->series->name }}</td><td>{{ $idea->format?->name ?? '—' }}</td><td>{{ $idea->submitter->name }}</td><td>{{ $idea->department->name }}</td><td>{{ $idea->status->label() }}</td><td>{{ $idea->created_at->format('d M Y') }}</td><td>@can('ideas.select')@if(!in_array($idea->status,[App\Enums\IdeaStatus::Converted,App\Enums\IdeaStatus::Archived]))<form method="post" action="{{ route('ideas.status',$idea) }}">@csrf @method('PATCH')<select data-testid="idea-status" name="status" onchange="this.form.submit()" class="field">@foreach(App\Enums\IdeaStatus::cases() as $s)@if($s!==App\Enums\IdeaStatus::Converted)<option value="{{ $s->value }}" @selected($idea->status===$s)>{{ $s->label() }}</option>@endif @endforeach</select></form>@endif @endcan @can('ideas.move_to_content')@if($idea->status===App\Enums\IdeaStatus::Selected&&!$idea->content)<details><summary data-testid="move-idea" class="text-blue-600 cursor-pointer">Move to Content Plan</summary><form method="post" action="{{ route('ideas.move',$idea) }}" class="grid gap-2 min-w-64 mt-2">@csrf<input type="hidden" name="title" value="{{ strip_tags($idea->idea) }}"><input type="hidden" name="pillar_id" value="{{ $idea->pillar_id }}"><input type="hidden" name="series_id" value="{{ $idea->series_id }}"><input data-testid="move-publish-date" class="field" type="date" name="publish_date"><select data-testid="move-account" class="field" name="account_id">@foreach($accounts as $x)<option value="{{ $x->id }}">{{ $x->name }}</option>@endforeach</select><select data-testid="move-format" class="field" name="format_id" required>@foreach($formats as $x)<option value="{{ $x->id }}" @selected($idea->format_id===$x->id)>{{ $x->name }}</option>@endforeach</select><select data-testid="move-pic" class="field" name="pic_user_id">@foreach($users as $x)<option value="{{ $x->id }}">{{ $x->name }}</option>@endforeach</select><label><input type="checkbox" name="platform_ids[]" value="{{ $platforms->first()->id }}" checked> {{ $platforms->first()->name }}</label><button data-testid="move-submit" class="btn btn-blue">Create Content</button></form></details>@endif @endcan</td></tr>@endforeach
 </tbody></table></div><div class="mt-4">{{ $ideas->links() }}</div>
 <div x-cloak x-show="open" class="fixed inset-0 bg-black/30 z-50 grid place-items-center p-4"><form method="post" action="{{ route('ideas.store') }}" class="bg-white rounded-xl p-6 w-full max-w-lg">@csrf<div class="flex justify-between mb-4"><h2 class="font-bold">Submit Idea</h2><button type="button" @click="open=false">✕</button></div><div class="flex gap-1 mb-1"><button type="button" class="btn border" onclick="document.execCommand('bold')"><b>B</b></button><button type="button" class="btn border" onclick="document.execCommand('italic')"><i>I</i></button><button type="button" class="btn border" onclick="document.execCommand('underline')"><u>U</u></button></div><div data-testid="idea-editor" contenteditable="true" class="field w-full min-h-28" @input="$refs.idea.value=$event.target.innerHTML"></div><input x-ref="idea" data-testid="idea-title" type="hidden" name="idea" required><select data-testid="idea-pillar" x-model="pillar" class="field w-full mt-2" name="pillar_id" required><option value="">Pillar</option>@foreach($pillars as $p)<option value="{{ $p->id }}">{{ $p->name }}</option>@endforeach</select><select data-testid="idea-series" class="field w-full mt-2" name="series_id" required><option value="">Series</option><template x-for="s in filterSeries()"><option :value="s.id" x-text="s.name"></option></template></select><select data-testid="idea-format" class="field w-full mt-2" name="format_id"><option value="">Format Content</option>@foreach($formats as $x)<option value="{{ $x->id }}">{{ $x->name }}</option>@endforeach</select><p class="text-xs text-slate-400 mt-3">Submitted By dan Department diambil otomatis dari akun Anda.</p><button data-testid="submit-idea" class="btn btn-blue mt-5">Submit Idea</button></form></div>
 @can('ideas.bulk_import')<dialog x-ref="bulk" class="rounded-xl p-6 backdrop:bg-black/30"><form method="post" enctype="multipart/form-data" action="{{ route('ideas.import') }}">@csrf<h2 class="font-bold mb-3">Bulk Upload Ideas</h2><input data-testid="ideas-file" type="file" name="file" accept=".xlsx,.csv" required><div class="mt-4 flex gap-2"><button data-testid="import-ideas" class="btn btn-blue">Validate & Import</button><button type="button" class="btn border" @click="$refs.bulk.close()">Cancel</button></div><p class="text-xs text-slate-400 mt-3">Atomic import: semua row valid atau tidak ada row disimpan.</p></form></dialog>@endcan
</div>
@endsection
