@extends('layouts.app')
@section('content')
@php($seriesData=$pillars->flatMap(fn($p)=>$p->series->map(fn($s)=>['id'=>$s->id,'name'=>$s->name,'pillar_id'=>$p->id]))->values())
<div x-data="{open:false,pillar:'{{ request('pillar_id') }}',series:@js($seriesData),forPillar(){return this.series.filter(s=>String(s.pillar_id)===String(this.pillar))}}"><div class="flex justify-between mb-5"><div><h1 class="text-2xl font-bold">Content Plan</h1><p class="text-xs text-slate-500">Database semua konten Kolabo</p></div>@can('content.create')<button data-testid="add-content" @click="open=true" class="btn btn-blue">+ Add Content</button>@endcan</div>
<form class="flex flex-wrap gap-2 mb-4"><input class="field" name="search" value="{{ request('search') }}" placeholder="Search content..."><select data-testid="filter-pillar" x-model="pillar" class="field" name="pillar_id"><option value="">Pillar</option>@foreach($pillars as $p)<option value="{{ $p->id }}">{{ $p->name }}</option>@endforeach</select><select data-testid="filter-series" class="field" name="series_id"><option value="">Series</option><template x-for="s in forPillar()"><option :value="s.id" x-text="s.name" :selected="String(s.id)==='{{ request('series_id') }}'"></option></template></select><select class="field" name="status"><option value="">Status</option>@foreach(App\Enums\ContentStatus::cases() as $s)<option value="{{ $s->value }}" @selected(request('status')===$s->value)>{{ $s->label() }}</option>@endforeach</select><button class="btn border">Filter</button><a class="btn border" href="{{ route('content.index') }}">Reset</a></form>
<div class="panel overflow-x-auto"><table class="table w-full"><thead><tr><th>No.</th><th>Judul</th><th>Publish</th><th>Account</th><th>Platform</th><th>Pillar</th><th>Series</th><th>Format</th><th>PIC</th><th>Status</th></tr></thead><tbody>@forelse($contents as $c)<tr data-testid="content-row"><td>{{ $contents->firstItem()+$loop->index }}</td><td><a class="font-semibold" href="{{ route('content.show',$c) }}">{{ $c->title }}</a></td><td>{{ $c->publish_date?->format('d M Y')??'—' }}</td><td>{{ $c->account?->name }}</td><td>{{ $c->platforms->pluck('name')->join(', ') }}</td><td>{{ $c->pillar->name }}</td><td>{{ $c->series->name }}</td><td>{{ $c->format?->name }}</td><td>{{ $c->pic?->name }}</td><td>@can('content.change_status')<select data-testid="content-status" data-url="{{ route('content.status',$c) }}" data-current="{{ $c->status->value }}" class="field status-select">@foreach(App\Enums\ContentStatus::cases() as $s)<option value="{{ $s->value }}" @selected($c->status===$s)>{{ $s->label() }}</option>@endforeach</select>@else<span class="badge bg-blue-50 text-blue-600">{{ $c->status->label() }}</span>@endcan</td></tr>@empty<tr><td colspan="10">Belum ada content.</td></tr>@endforelse</tbody></table></div><div class="mt-4">{{ $contents->links() }}</div>
<div x-cloak x-show="open" class="fixed inset-0 bg-black/30 z-50 grid place-items-center p-4"><form method="post" action="{{ route('content.store') }}" class="bg-white rounded-xl p-6 w-full max-w-2xl">@csrf<h2 class="font-bold mb-4">Add Content</h2><div class="grid md:grid-cols-2 gap-3"><input class="field md:col-span-2" name="title" placeholder="Title" required><input class="field" type="date" name="publish_date"><select class="field" name="account_id">@foreach($accounts as $x)<option value="{{ $x->id }}">{{ $x->name }}</option>@endforeach</select><select data-testid="content-pillar" x-model="pillar" class="field" name="pillar_id" required><option value="">Pillar</option>@foreach($pillars as $p)<option value="{{ $p->id }}">{{ $p->name }}</option>@endforeach</select><select data-testid="content-series" class="field" name="series_id" required><option value="">Series</option><template x-for="s in forPillar()"><option :value="s.id" x-text="s.name"></option></template></select><select class="field" name="format_id">@foreach($formats as $x)<option value="{{ $x->id }}">{{ $x->name }}</option>@endforeach</select><select class="field" name="pic_user_id">@foreach($users as $x)<option value="{{ $x->id }}">{{ $x->name }}</option>@endforeach</select><div class="md:col-span-2">@foreach($platforms as $x)<label class="mr-3 text-xs"><input type="checkbox" name="platform_ids[]" value="{{ $x->id }}"> {{ $x->name }}</label>@endforeach</div></div><button class="btn btn-blue mt-4">Create Planned Content</button></form></div></div>
@endsection
@push('scripts')<script>document.querySelectorAll('.status-select').forEach(el=>el.addEventListener('change',async()=>{const old=el.dataset.current;const r=await fetch(el.dataset.url,{method:'PATCH',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]').content},body:JSON.stringify({status:el.value})});if(!r.ok){el.value=old;alert((await r.json()).message||'This status transition is not allowed.');}else{el.dataset.current=el.value;alert('Status updated successfully');}}));</script>@endpush
