@extends('layouts.app')
@section('content')
<a href="{{ route('content.index') }}" class="text-xs text-slate-500">← Content Plan</a><div class="mt-4 mb-5"><h1 class="text-2xl font-bold">{{ $content->title }}</h1><span class="badge bg-blue-50 text-blue-600">{{ $content->status->label() }}</span></div>
<div class="grid lg:grid-cols-3 gap-4"><section class="panel p-5 lg:col-span-2" x-data="{tab:'brief'}"><div class="flex gap-4 border-b mb-5 overflow-auto">@foreach(['brief'=>'Brief','script'=>'Script / Copy','assets'=>'Assets','comments'=>'Comments','revision'=>'Revision','activity'=>'Activity','source'=>'Source'] as $k=>$v)<button data-testid="tab-{{ $k }}" @click="tab='{{ $k }}'" class="pb-3 text-xs">{{ $v }}</button>@endforeach</div>
<form x-show="tab==='brief'" method="post" action="{{ route('content.brief',$content) }}" class="grid gap-3">@csrf @method('PUT')@foreach(['hook'=>'Hook','angle'=>'Angle','key_message'=>'Key Message','cta'=>'CTA','notes'=>'Notes'] as $k=>$v)<label class="text-xs font-semibold">{{ $v }}<textarea class="field w-full" name="{{ $k }}" @disabled(!auth()->user()->can('content.edit'))>{{ $content->brief?->$k }}</textarea></label>@endforeach @can('content.edit')<button class="btn btn-blue">Save Brief</button>@endcan</form>
<form x-show="tab==='script'" method="post" action="{{ route('content.brief',$content) }}" class="grid gap-3">@csrf @method('PUT')@foreach(['main_copy'=>'Main Script / Copy','reels_script'=>'Reels Script','carousel_copy'=>'Carousel Copy','caption'=>'Caption','threads_copy'=>'Threads Copy'] as $k=>$v)<label class="text-xs font-semibold">{{ $v }}<textarea class="field w-full h-28" name="{{ $k }}" @disabled(!auth()->user()->can('content.edit'))>{{ $content->brief?->$k }}</textarea></label>@endforeach @can('content.edit')<button class="btn btn-blue">Save Script / Copy</button>@endcan</form>
<div x-show="tab==='assets'">@foreach($content->assets as $x)<a href="{{ $x->url }}" target="_blank" class="block border rounded p-3 mb-2"><b>{{ $x->title }}</b><div class="text-xs">{{ $x->asset_type }} · {{ $x->addedBy->name }} · {{ $x->created_at->format('d M Y H:i') }}</div><p class="text-xs">{{ $x->notes }}</p></a>@endforeach @can('assets.create')<form method="post" action="{{ route('content.assets',$content) }}" class="grid gap-2 mt-4">@csrf<input class="field" name="title" placeholder="Asset Name" required><select class="field" name="asset_type">@foreach(['Figma','Google Drive','Raw Footage','Reference','Image','Video','Thumbnail','Other'] as $x)<option>{{ $x }}</option>@endforeach</select><input class="field" type="url" name="url" placeholder="External URL" required><textarea class="field" name="notes" placeholder="Notes"></textarea><button class="btn btn-blue">Add Asset Reference</button></form>@endcan</div>
<div x-show="tab==='comments'">@foreach($content->comments as $x)<div data-testid="comment" class="border rounded p-3 mb-2"><b>{{ $x->user->name }}</b><span class="text-xs text-slate-400"> · {{ $x->created_at->format('d M Y · H:i') }}</span><p class="mt-2 text-sm whitespace-pre-wrap">{{ $x->body }}</p></div>@endforeach @can('comments.create')<form method="post" action="{{ route('content.comments',$content) }}">@csrf<textarea data-testid="comment-body" class="field w-full" name="body" required></textarea><button data-testid="comment-submit" class="btn btn-blue mt-2">Add Comment</button></form>@endcan</div>
<div x-show="tab==='revision'">@foreach($content->revisions as $x)<div class="border rounded p-3 mb-2">{{ $x->note }}<div class="text-xs">{{ $x->author->name }}</div></div>@endforeach @if($content->status===App\Enums\ContentStatus::Review&&auth()->user()->can('production.change_status'))<form method="post" action="{{ route('content.revision',$content) }}">@csrf<textarea data-testid="revision-comment" class="field w-full" name="body" placeholder="Revision Comment"></textarea><button data-testid="request-revision" class="btn bg-amber-500 text-white mt-2">Request Revision</button></form>@endif</div>
<div x-show="tab==='activity'">@foreach($activities as $a)<div class="border-l-2 pl-3 py-2 text-sm">{{ $a->description }}<div class="text-xs">{{ $a->created_at->diffForHumans() }}</div></div>@endforeach</div>
<div x-show="tab==='source'">@if($content->sourceIdea)<div class="bg-slate-50 p-4 text-sm"><b>Submitted By:</b> {{ $content->sourceIdea->submitter->name }}<br><b>Department:</b> {{ $content->sourceIdea->department->name }}<br><b>Original Idea:</b> {!! $content->sourceIdea->idea !!}<br><b>Converted At:</b> {{ $content->created_at->format('d M Y H:i') }}</div>@else<p>Source: Direct Content</p>@endif</div></section>
<aside class="panel p-5"><h2 class="font-bold mb-3">Content Metadata</h2>@foreach(['Publish Date'=>$content->publish_date?->format('d M Y'),'Account'=>$content->account?->name,'Platform'=>$content->platforms->pluck('name')->join(', '),'Pillar'=>$content->pillar->name,'Series'=>$content->series->name,'Format'=>$content->format?->name,'PIC'=>$content->pic?->name] as $k=>$v)<div class="flex justify-between py-3 border-b text-xs"><span>{{ $k }}</span><b>{{ $v?:'—' }}</b></div>@endforeach</aside></div>
@endsection
