import {test,expect} from '@playwright/test';
import {login,logout,failOnPageErrors} from './helpers';
test('Idea multi-platform → bulk conversion → flexible Production → Published',async({page})=>{
 test.setTimeout(120_000);const noErrors=failOnPageErrors(page);const title=`Revision Two ${Date.now()}`;
 await login(page,'sales@kolabo.id');await expect(page.getByRole('heading',{name:'Sales Dashboard'})).toBeVisible();await page.getByRole('link',{name:'Ideas'}).click();await page.getByTestId('add-idea').click();await page.getByTestId('idea-editor').fill(title);await page.getByTestId('idea-platform-instagram').check();await page.getByTestId('idea-pillar').selectOption({label:'Entertainment'});await page.getByTestId('idea-series').selectOption({label:'POV'});await page.getByTestId('idea-format').selectOption({label:'Reels'});await page.getByTestId('idea-hook').fill('Sales brief');await page.getByTestId('idea-script').fill('Sales script');await page.getByTestId('submit-idea').click();
 let row=page.getByTestId('idea-row').filter({hasText:title});await expect(row).toContainText('Andi Sales');await logout(page);
 await login(page,'lead@kolabo.id');await page.getByRole('link',{name:'Ideas'}).click();row=page.getByTestId('idea-row').filter({hasText:title});await row.getByTestId('idea-status').selectOption('consider');row=page.getByTestId('idea-row').filter({hasText:title});await row.getByTestId('idea-select').check();await page.getByTestId('bulk-move-button').evaluate((button:HTMLButtonElement)=>button.click());
 const item=page.getByTestId('move-modal').locator('section').filter({hasText:title});await item.getByTestId('move-publish-date').fill('2026-08-24');await item.getByTestId('move-pic').selectOption({label:'Dina Lead'});await item.getByTestId('move-account-instagram').selectOption({index:1});await page.getByTestId('move-now').evaluate((button:HTMLButtonElement)=>button.form!.submit());
 await page.getByPlaceholder('Search content').fill(title);await page.getByRole('button',{name:'Filter'}).click();row=page.getByTestId('content-row').filter({hasText:title});await expect(row).toContainText('Planned');await row.getByRole('link',{name:title}).click();await page.getByTestId('tab-source').click();await expect(page.getByText('Andi Sales')).toBeVisible();
 const id=page.url().split('/').pop()!;const update=(status:string)=>page.evaluate(async({id,status})=>(await fetch(`/production/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':document.querySelector<HTMLMetaElement>('meta[name="csrf-token"]')!.content},body:JSON.stringify({status})})).ok,{id,status});for(const status of ['scheduled','in_production','published','review','planned','published'])expect(await update(status)).toBe(true);noErrors();
});
