import{test,expect}from'@playwright/test';import{login}from'./helpers';
test('Sales dashboard request creates urgent multi-platform Idea',async({page})=>{
 const title=`Urgent Request ${Date.now()}`;await login(page,'sales@kolabo.id');await expect(page).toHaveURL(/sales-dashboard/);await expect(page.getByTestId('workload-card').first()).toBeVisible();await page.getByTestId('request-content').click();const box=await page.getByTestId('request-modal').locator('form').boundingBox();const v=page.viewportSize()!;expect(Math.abs(box!.x+box!.width/2-v.width/2)).toBeLessThan(40);await page.getByTestId('request-title').fill(title);await page.getByTestId('request-platform-instagram').check();await page.getByTestId('request-platform-tiktok').check();await page.locator('[data-testid="request-modal"] select[name="pillar_id"]').selectOption({label:'Product'});await page.locator('[data-testid="request-modal"] select[name="series_id"]').selectOption({label:'Kolabo Features'});await page.getByTestId('urgent-toggle').check();await page.locator('[data-testid="request-modal"] input[name="needed_at"]').fill('2026-08-21T10:00');await page.locator('[data-testid="request-modal"] textarea[name="urgent_purpose"]').fill('Enterprise presentation');await page.getByTestId('request-submit').click();await expect(page.getByRole('heading',{name:title})).toBeVisible();await expect(page.getByText('URGENT REQUEST',{exact:true})).toBeVisible();await expect(page.getByText('Enterprise presentation')).toBeVisible();
});
test('Idea selection count is UI state and Selected status is absent',async({page})=>{await login(page,'lead@kolabo.id');await page.getByRole('link',{name:'Ideas'}).click();for(let i=0;i<2;i++){await page.getByTestId('add-idea').click();await page.getByTestId('idea-editor').fill(`Select UI ${Date.now()} ${i}`);await page.getByTestId('idea-platform-instagram').check();await page.getByTestId('idea-pillar').selectOption({label:'Product'});await page.getByTestId('idea-series').selectOption({label:'Kolabo Features'});await page.getByTestId('submit-idea').click();}const selects=page.getByTestId('idea-select');await selects.nth(0).check();await selects.nth(1).check();await expect(page.getByTestId('bulk-move-button')).toContainText('(2)');for(let i=0;i<await page.getByTestId('idea-status').count();i++)await expect(page.getByTestId('idea-status').nth(i).locator('option',{hasText:'Selected'})).toHaveCount(0);});
test('Admin creates multiple social accounts per platform',async({page})=>{const unique=Date.now();await login(page,'admin@kolabo.id');await page.getByRole('link',{name:'Accounts'}).click();for(const suffix of ['a','b']){await page.getByTestId('add-account').click();await page.getByTestId('account-platform').selectOption({label:'Instagram'});await page.getByTestId('account-name').fill(`PW ${unique}-${suffix}`);await page.getByTestId('account-username').fill(`@pw-${unique}-${suffix}`);await page.getByTestId('account-submit').click();}await expect(page.getByTestId('account-row').filter({hasText:`PW ${unique}-a`})).toContainText('Instagram');await expect(page.getByTestId('account-row').filter({hasText:`PW ${unique}-b`})).toContainText('Instagram');});

test('Account trash action is accessible and confirmation protects deletion',async({page})=>{
 const unique=Date.now();const accountName=`Delete PW ${unique}`;await login(page,'admin@kolabo.id');await page.goto('/admin/accounts');await page.getByTestId('add-account').click();await page.getByTestId('account-platform').selectOption({label:'Instagram'});await page.getByTestId('account-name').fill(accountName);await page.getByTestId('account-username').fill(`@delete-pw-${unique}`);await page.getByTestId('account-submit').click();let row=page.getByTestId('account-row').filter({hasText:accountName});const remove=row.getByTestId('delete-account');await expect(remove).toHaveAttribute('aria-label','Delete account');await expect(remove).toHaveAttribute('title','Delete');await expect(remove.locator('svg')).toBeVisible();page.once('dialog',dialog=>dialog.dismiss());await remove.click();await expect(row).toBeVisible();page.once('dialog',dialog=>dialog.accept());await remove.click();await expect(page.getByTestId('account-row').filter({hasText:accountName})).toHaveCount(0);
});
