<?php
use App\Http\Controllers\Auth\SessionController;
use App\Http\Controllers\{IdeasImportController,KolaboController,RevisionOneController,RevisionTwoController};
use Illuminate\Support\Facades\Route;

Route::middleware('guest')->group(function(){Route::get('/login',[SessionController::class,'create'])->name('login');Route::post('/login',[SessionController::class,'store']);});
Route::middleware('auth')->group(function(){
 Route::post('/logout',[SessionController::class,'destroy'])->name('logout');
 Route::get('/',fn()=>auth()->user()->can('dashboard.view')?redirect()->route('dashboard'):redirect()->route('sales-dashboard'));
 Route::get('/dashboard',[KolaboController::class,'dashboard'])->name('dashboard');
 Route::get('/sales-dashboard',[RevisionTwoController::class,'salesDashboard'])->name('sales-dashboard');
 Route::post('/content-requests',[RevisionTwoController::class,'requestContent'])->name('content-requests.store');
 Route::get('/content',[KolaboController::class,'contents'])->name('content.index');Route::post('/content',[KolaboController::class,'storeContent'])->name('content.store');Route::get('/content/{content}',[KolaboController::class,'showContent'])->name('content.show');Route::patch('/content/{content}/status',[RevisionOneController::class,'updateContentStatus'])->name('content.status');Route::put('/content/{content}/brief',[RevisionOneController::class,'brief'])->name('content.brief');Route::post('/content/{content}/assets',[RevisionOneController::class,'asset'])->name('content.assets');Route::post('/content/{content}/comments',[RevisionOneController::class,'comment'])->name('content.comments');Route::patch('/content/{content}/comments/{comment}/resolve',[RevisionOneController::class,'resolveComment'])->name('content.comments.resolve');Route::post('/content/{content}/revision',[RevisionOneController::class,'revision'])->name('content.revision');
 Route::get('/ideas',[KolaboController::class,'ideas'])->name('ideas.index');Route::post('/ideas',[RevisionTwoController::class,'storeIdea'])->name('ideas.store');Route::get('/ideas/{idea}',[RevisionTwoController::class,'showIdea'])->name('ideas.show');Route::patch('/ideas/{idea}/status',[KolaboController::class,'ideaStatus'])->name('ideas.status');Route::post('/ideas/{idea}/move',[KolaboController::class,'moveIdea'])->name('ideas.move');Route::post('/ideas-bulk-move',[RevisionTwoController::class,'bulkMove'])->name('ideas.bulk-move');
 Route::get('/ideas-template',[IdeasImportController::class,'template'])->name('ideas.template');Route::post('/ideas-preview',[IdeasImportController::class,'preview'])->name('ideas.preview');Route::post('/ideas-import',[IdeasImportController::class,'import'])->name('ideas.import');
 Route::get('/calendar',[KolaboController::class,'calendar'])->name('calendar');Route::patch('/calendar/{content}',[KolaboController::class,'updateDate'])->name('calendar.update');Route::get('/production',[KolaboController::class,'production'])->name('production');Route::patch('/production/{content}',[KolaboController::class,'updateStatus'])->name('production.update');Route::get('/published',[KolaboController::class,'published'])->name('published');Route::get('/my-tasks',[KolaboController::class,'myTasks'])->name('my-tasks');Route::get('/team',[KolaboController::class,'team'])->name('team');Route::get('/assets',[KolaboController::class,'assets'])->name('assets');Route::post('/assets',[KolaboController::class,'storeAsset'])->name('assets.store');
 Route::get('/admin/users',[KolaboController::class,'users'])->name('users');Route::post('/admin/users',[KolaboController::class,'storeUser'])->name('users.store');Route::patch('/admin/users/{user}/toggle',[KolaboController::class,'toggleUser'])->name('users.toggle');Route::put('/admin/users/{user}',[RevisionTwoController::class,'updateUser'])->name('users.update');Route::put('/admin/users/{user}/password',[RevisionTwoController::class,'password'])->name('users.password');Route::delete('/admin/users/{user}',[RevisionTwoController::class,'deleteUser'])->name('users.delete');
 Route::get('/admin/roles',[RevisionOneController::class,'roles'])->name('roles');Route::post('/admin/roles',[RevisionOneController::class,'roleStore'])->name('roles.store');Route::put('/admin/roles/{role}',[RevisionOneController::class,'roleUpdate'])->name('roles.update');Route::delete('/admin/roles/{role}',[RevisionTwoController::class,'deleteRole'])->name('roles.delete');
 Route::get('/admin/accounts',[RevisionTwoController::class,'accounts'])->name('accounts');Route::post('/admin/accounts',[RevisionTwoController::class,'storeAccount'])->name('accounts.store');Route::put('/admin/accounts/{account}',[RevisionTwoController::class,'updateAccount'])->name('accounts.update');Route::patch('/admin/accounts/{account}/toggle',[RevisionTwoController::class,'toggleAccount'])->name('accounts.toggle');Route::delete('/admin/accounts/{account}',[RevisionTwoController::class,'deleteAccount'])->name('accounts.delete');
 Route::get('/admin/masters',[RevisionOneController::class,'masters'])->name('masters');Route::post('/admin/pillars',[RevisionOneController::class,'pillar'])->name('pillars.store');Route::put('/admin/pillars/{pillar}',[RevisionOneController::class,'pillar'])->name('pillars.update');Route::post('/admin/series',[RevisionOneController::class,'series'])->name('series.store');Route::put('/admin/series/{series}',[RevisionOneController::class,'series'])->name('series.update');Route::post('/admin/formats',[RevisionOneController::class,'format'])->name('formats.store');Route::put('/admin/formats/{format}',[RevisionOneController::class,'format'])->name('formats.update');Route::patch('/admin/masters/{type}/{id}/toggle',[RevisionOneController::class,'toggle'])->name('masters.toggle');
});
