<?php
namespace Tests\Feature;
use App\Models\{Account,Content,Format,Idea,Pillar,Platform,User};
use Database\Seeders\DatabaseSeeder;use Illuminate\Foundation\Testing\RefreshDatabase;use Spatie\Permission\Models\Role;use Tests\TestCase;
class KolaboCriticalFlowTest extends TestCase
{
 use RefreshDatabase;protected function setUp():void{parent::setUp();$this->seed(DatabaseSeeder::class);}
 private function ideaData(string $title='Test Idea'):array{$pillar=Pillar::whereName('Product')->first();return ['idea'=>$title,'pillar_id'=>$pillar->id,'series_id'=>$pillar->series()->first()->id,'format_id'=>Format::first()->id,'platform_ids'=>[Platform::whereName('Instagram')->value('id')]];}
 public function test_sales_lands_on_read_only_sales_dashboard():void{$sales=User::whereEmail('sales@kolabo.id')->first();$this->actingAs($sales)->get('/sales-dashboard')->assertOk()->assertSee('Sales Dashboard')->assertSee('Fadly Creative');$this->actingAs($sales)->get('/dashboard')->assertForbidden();$this->actingAs($sales)->get('/production')->assertForbidden();}
 public function test_sales_attribution_is_server_controlled_and_platforms_persist():void{$sales=User::whereEmail('sales@kolabo.id')->first();$payload=$this->ideaData('Sales insight')+['submitted_by'=>User::first()->id];$this->actingAs($sales)->post('/ideas',$payload)->assertRedirect();$idea=Idea::whereIdea('Sales insight')->firstOrFail();$this->assertSame($sales->id,$idea->submitted_by);$this->assertSame($sales->department_id,$idea->source_department_id);$this->assertCount(1,$idea->platforms);}
 public function test_urgent_content_request_requires_and_stores_metadata():void{$sales=User::whereEmail('sales@kolabo.id')->first();$this->actingAs($sales)->post('/content-requests',$this->ideaData('Urgent Request')+['is_urgent'=>1])->assertSessionHasErrors(['needed_at','urgent_purpose']);$this->actingAs($sales)->post('/content-requests',$this->ideaData('Urgent Request')+['is_urgent'=>1,'needed_at'=>'2026-08-21 10:00','urgent_purpose'=>'Enterprise presentation'])->assertRedirect();$this->assertDatabaseHas('ideas',['idea'=>'Urgent Request','submitted_by'=>$sales->id,'source_department_id'=>$sales->department_id,'is_content_request'=>1,'is_urgent'=>1,'urgent_purpose'=>'Enterprise presentation']);}
 public function test_selected_status_is_obsolete():void{$lead=User::whereEmail('lead@kolabo.id')->first();$idea=Idea::first();$this->actingAs($lead)->patch('/ideas/'.$idea->id.'/status',['status'=>'selected'])->assertSessionHasErrors('status');}
 public function test_bulk_move_creates_one_planned_content_per_idea_transactionally():void{$lead=User::whereEmail('lead@kolabo.id')->first();$platform=Platform::whereName('Instagram')->first();$account=Account::where('platform_id',$platform->id)->first();$ideas=collect(['Bulk One','Bulk Two'])->map(function($title)use($lead,$platform){$data=$this->ideaData($title);$idea=Idea::create(['idea'=>$title,'pillar_id'=>$data['pillar_id'],'series_id'=>$data['series_id'],'format_id'=>$data['format_id'],'submitted_by'=>$lead->id,'source_department_id'=>$lead->department_id,'status'=>'new']);$idea->platforms()->sync([$platform->id]);return $idea;});$items=$ideas->mapWithKeys(fn($idea)=>[$idea->id=>['idea_id'=>$idea->id,'publish_date'=>'2026-08-24','pic_user_id'=>$lead->id,'accounts'=>[$platform->id=>$account->id]]])->all();$this->actingAs($lead)->post('/ideas-bulk-move',compact('items'))->assertRedirect('/content');$this->assertSame(2,Content::whereIn('source_idea_id',$ideas->pluck('id'))->where('status','planned')->count());$this->assertSame(2,Idea::whereIn('id',$ideas->pluck('id'))->where('status','converted')->count());}
 public function test_account_platform_mismatch_rejects_entire_batch():void{$lead=User::whereEmail('lead@kolabo.id')->first();$idea=Idea::first();$platform=$idea->platforms->first();$wrong=Account::where('platform_id','!=',$platform->id)->first();$this->actingAs($lead)->post('/ideas-bulk-move',['items'=>[$idea->id=>['idea_id'=>$idea->id,'publish_date'=>'2026-08-24','pic_user_id'=>$lead->id,'accounts'=>[$platform->id=>$wrong->id]]]])->assertStatus(422);$this->assertDatabaseMissing('contents',['source_idea_id'=>$idea->id]);}
 public function test_flexible_kanban_and_calendar_authorization_remain():void{$lead=User::whereEmail('lead@kolabo.id')->first();$content=Content::first();foreach(['published','planned','review','scheduled','in_production'] as $status)$this->actingAs($lead)->patchJson('/production/'.$content->id,['status'=>$status])->assertOk();$sales=User::whereEmail('sales@kolabo.id')->first();$this->actingAs($sales)->patchJson('/calendar/'.$content->id,['publish_date'=>'2026-09-01'])->assertForbidden();}
 public function test_social_accounts_support_many_per_platform_and_safe_delete():void{$admin=User::whereEmail('admin@kolabo.id')->first();$platform=Platform::whereName('Instagram')->first();$this->actingAs($admin)->post('/admin/accounts',['platform_id'=>$platform->id,'account_name'=>'Test','username'=>'@test','is_active'=>1])->assertRedirect();$account=Account::whereUsername('@test')->firstOrFail();$this->actingAs($admin)->delete('/admin/accounts/'.$account->id)->assertRedirect();$this->assertSoftDeleted('accounts',['id'=>$account->id]);}
 public function test_super_admin_user_and_role_are_protected():void{$admin=User::whereEmail('admin@kolabo.id')->first();$role=Role::whereName('Super Admin')->first();$this->actingAs($admin)->patch('/admin/users/'.$admin->id.'/toggle')->assertStatus(422);$this->actingAs($admin)->delete('/admin/users/'.$admin->id)->assertStatus(422);$this->actingAs($admin)->delete('/admin/roles/'.$role->id)->assertStatus(422);}
 public function test_unused_role_can_delete_but_assigned_role_cannot():void{$admin=User::whereEmail('admin@kolabo.id')->first();$unused=Role::create(['name'=>'Unused Test','is_active'=>true]);$this->actingAs($admin)->delete('/admin/roles/'.$unused->id)->assertRedirect();$this->assertDatabaseMissing('roles',['id'=>$unused->id]);$assigned=Role::whereName('Sales Contributor')->first();$this->actingAs($admin)->delete('/admin/roles/'.$assigned->id)->assertStatus(422);}
 public function test_normal_user_can_be_edited_password_changed_and_soft_deleted():void{$admin=User::whereEmail('admin@kolabo.id')->first();$user=User::whereEmail('sales@kolabo.id')->first();$this->actingAs($admin)->put('/admin/users/'.$user->id,['name'=>'Sales Updated','email'=>'sales-updated@kolabo.id','department_id'=>$user->department_id,'role'=>'Sales Contributor'])->assertRedirect();$this->actingAs($admin)->put('/admin/users/'.$user->id.'/password',['password'=>'new-password','password_confirmation'=>'new-password'])->assertRedirect();$this->actingAs($admin)->delete('/admin/users/'.$user->id)->assertRedirect();$this->assertSoftDeleted('users',['id'=>$user->id]);$this->assertSame('Sales Updated',Idea::first()->submitter->name);}
 public function test_admin_routes_and_published_library_render():void{$admin=User::whereEmail('admin@kolabo.id')->first();foreach(['/dashboard','/ideas','/content','/production','/calendar','/published','/admin/users','/admin/roles','/admin/accounts','/admin/masters'] as $url)$this->actingAs($admin)->get($url)->assertOk();}
}
