<?php
namespace Tests\Feature;
use App\Models\{Account,Content,Format,Idea,Pillar,Platform,User};use Database\Seeders\DatabaseSeeder;use Illuminate\Foundation\Testing\RefreshDatabase;use Tests\TestCase;
class KolaboCriticalFlowTest extends TestCase{use RefreshDatabase;protected function setUp():void{parent::setUp();$this->seed(DatabaseSeeder::class);}
 public function test_sales_permissions_and_server_controlled_attribution():void{$sales=User::whereEmail('sales@kolabo.id')->first();$this->actingAs($sales)->get('/admin/users')->assertForbidden();$pillar=Pillar::whereName('Product')->first();$series=$pillar->series()->first();$this->actingAs($sales)->post('/ideas',['idea'=>'<b>Sales insight</b><script>alert(1)</script>','pillar_id'=>$pillar->id,'series_id'=>$series->id,'format_id'=>Format::first()->id,'submitted_by'=>User::first()->id])->assertRedirect();$idea=Idea::where('idea','like','%Sales insight%')->first();$this->assertSame($sales->id,$idea->submitted_by);$this->assertSame($sales->department_id,$idea->source_department_id);$this->assertStringNotContainsString('<script>',$idea->idea);}
 public function test_series_must_belong_to_pillar():void{$sales=User::whereEmail('sales@kolabo.id')->first();$product=Pillar::whereName('Product')->first();$pov=Pillar::whereName('Entertainment')->first()->series()->whereName('POV')->first();$this->actingAs($sales)->post('/ideas',['idea'=>'Invalid','pillar_id'=>$product->id,'series_id'=>$pov->id])->assertSessionHasErrors('series_id');}
 public function test_conversion_marks_idea_converted_and_preserves_format():void{$lead=User::whereEmail('lead@kolabo.id')->first();$idea=Idea::first();$idea->update(['status'=>'selected']);$this->actingAs($lead)->post('/ideas/'.$idea->id.'/move',['title'=>'Converted Idea','publish_date'=>'2026-09-01','account_id'=>Account::first()->id,'pillar_id'=>$idea->pillar_id,'series_id'=>$idea->series_id,'format_id'=>$idea->format_id,'pic_user_id'=>$lead->id,'platform_ids'=>[Platform::first()->id]])->assertRedirect('/content');$content=Content::whereTitle('Converted Idea')->first();$this->assertSame('converted',$idea->fresh()->status->value);$this->assertSame('planned',$content->status->value);$this->assertSame($idea->format_id,$content->format_id);}
 public function test_content_transition_rules_are_enforced():void{$lead=User::whereEmail('lead@kolabo.id')->first();$content=Content::whereStatus('planned')->first();$this->actingAs($lead)->patchJson('/production/'.$content->id,['status'=>'published'])->assertStatus(422);$this->actingAs($lead)->patchJson('/production/'.$content->id,['status'=>'in_production'])->assertOk();$this->assertDatabaseHas('contents',['id'=>$content->id,'status'=>'in_production']);}
 public function test_revision_creates_comment_and_returns_to_production():void{$lead=User::whereEmail('lead@kolabo.id')->first();$content=Content::whereStatus('review')->first();$this->actingAs($lead)->post('/content/'.$content->id.'/revision',['body'=>'Opening dipercepat'])->assertRedirect();$this->assertDatabaseHas('content_comments',['content_id'=>$content->id,'user_id'=>$lead->id,'body'=>'Opening dipercepat']);$this->assertSame('in_production',$content->fresh()->status->value);}
 public function test_calendar_authorization_and_published_library():void{$sales=User::whereEmail('sales@kolabo.id')->first();$this->actingAs($sales)->patchJson('/calendar/'.Content::first()->id,['publish_date'=>'2026-09-01'])->assertForbidden();$lead=User::whereEmail('lead@kolabo.id')->first();$content=Content::whereStatus('scheduled')->first();$this->actingAs($lead)->patchJson('/production/'.$content->id,['status'=>'published'])->assertOk();$this->actingAs($lead)->get('/published')->assertSee($content->title);}
}
