<?php
namespace App\Http\Controllers;
use App\Models\{Format,Idea,IdeaAsset,IdeaBrief,Pillar};use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Validation\ValidationException;use ZipArchive;
class IdeasImportController extends Controller{
 private const TYPES=['Figma','Google Drive','Image','Video','Raw Footage','Reference','Thumbnail','Other'];
 private const HEADINGS=['idea'=>['idea','title','idea title'],'pillar'=>['pillar','content pillar'],'series'=>['series','content series'],'format'=>['format','content format'],'brief'=>['brief','hook','brief hook'],'script'=>['script copy','script','copy'],'asset_name'=>['asset name'],'asset_type'=>['asset type'],'asset_url'=>['asset url','asset link']];
 public function template(Request $r){abort_unless($r->user()->can('ideas.bulk_import'),403);$rows=[['Idea','Pillar','Series','Format','Brief','Script / Copy','Asset Name','Asset Type','Asset URL'],['Tips Follow Up Lead','Insight / Education','Tips','Reels','3 cara follow-up lead tanpa terlihat spam','Opening dimulai dari problem lead tidak membalas...','Sales Reference','Google Drive','https://drive.google.com/example'],['POV Sales Meeting','Entertainment','POV','Short Video','Situasi meeting sales yang relatable','POV saat target berubah di tengah bulan','Moodboard','Figma','https://figma.com/example']];$tmp=tempnam(sys_get_temp_dir(),'ideas').'.xlsx';$this->writeXlsx($tmp,$rows);return response()->download($tmp,'kolabo-ideas-template.xlsx')->deleteFileAfterSend(true);}
 public function preview(Request $r){abort_unless($r->user()->can('ideas.bulk_import'),403);$r->validate(['file'=>'required|file|extensions:xlsx,csv|max:5120']);$file=$r->file('file');$rows=strtolower($file->getClientOriginalExtension())==='csv'?$this->readCsv($file->getRealPath()):$this->readXlsx($file->getRealPath());[$header,$map]=$this->headingMap($rows);$preview=[];foreach(array_slice($rows,$header+1,null,true) as $i=>$row){if($this->emptyRow($row))continue;$preview[]=$this->validateRow($this->mapRow($row,$map),$i+1);}$r->session()->put('ideas_import_preview',$preview);return view('ideas.preview',['rows'=>$preview,'valid'=>collect($preview)->where('valid',true)->count()]);}
 public function import(Request $r){abort_unless($r->user()->can('ideas.bulk_import'),403);$rows=collect($r->session()->pull('ideas_import_preview',[]))->where('valid',true);DB::transaction(function()use($rows,$r){foreach($rows as $row){$d=$row['data'];$idea=Idea::create(['idea'=>strip_tags($d['idea'],'<b><strong><i><em><u><br><p>'),'pillar_id'=>$d['pillar_id'],'series_id'=>$d['series_id'],'format_id'=>$d['format_id'],'submitted_by'=>$r->user()->id,'source_department_id'=>$r->user()->department_id,'status'=>'new']);IdeaBrief::create(['idea_id'=>$idea->id,'notes'=>$d['brief'],'script_copy'=>strip_tags($d['script'],'<b><strong><i><em><u><br><p>')]);if($d['asset_url'])IdeaAsset::create(['idea_id'=>$idea->id,'name'=>$d['asset_name'],'type'=>$d['asset_type'],'url'=>$d['asset_url']]);}});return redirect()->route('ideas.index')->with('success',$rows->count().' valid ideas imported successfully.');}
 private function headingMap(array $rows):array{foreach($rows as $i=>$row){$normalized=array_map(fn($v)=>$this->normalizeHeading($v),$row);$map=[];foreach(self::HEADINGS as $field=>$aliases)foreach($aliases as $alias){$column=array_search($alias,$normalized,true);if($column!==false){$map[$field]=$column;break;}}if(isset($map['idea'],$map['pillar'],$map['series'],$map['format']))return[$i,$map];}throw ValidationException::withMessages(['file'=>'Header Idea, Pillar, Series, and Format could not be found. Please use the latest Excel template.']);}
 private function normalizeHeading(mixed $v):string{$v=preg_replace('/^\xEF\xBB\xBF/','',(string)$v);return preg_replace('/\s+/',' ',strtolower(trim(preg_replace('/[^\pL\pN]+/u',' ',$v))));}
 private function mapRow(array $row,array $map):array{return array_map(fn($field)=>trim((string)($row[$map[$field]??-1]??'')),array_keys(self::HEADINGS));}
 private function emptyRow(array $row):bool{foreach($row as $v)if(trim((string)$v)!=='')return false;return true;}
 private function validateRow(array $r,int $line):array{[$idea,$pillarName,$seriesName,$formatName,$brief,$script,$assetName,$assetType,$assetUrl]=$r;$errors=[];$pillar=Pillar::whereName(trim($pillarName))->where('is_active',true)->first();$series=$pillar?->series()->whereName(trim($seriesName))->where('is_active',true)->first();$format=Format::whereName(trim($formatName))->where('is_active',true)->first();if(!trim($idea))$errors[]='Idea is required.';if(!$pillar)$errors[]="Pillar \"$pillarName\" is invalid.";elseif(!$series)$errors[]="Series \"$seriesName\" does not belong to Pillar \"$pillarName\".";if(!$format)$errors[]="Format \"$formatName\" is invalid.";if($assetUrl&&!filter_var($assetUrl,FILTER_VALIDATE_URL))$errors[]='Asset URL is invalid.';if($assetUrl&&!in_array($assetType,self::TYPES,true))$errors[]='Asset Type is invalid.';return ['row'=>$line,'valid'=>!$errors,'errors'=>$errors,'display'=>compact('idea','pillarName','seriesName','formatName'),'data'=>['idea'=>$idea,'pillar_id'=>$pillar?->id,'series_id'=>$series?->id,'format_id'=>$format?->id,'brief'=>$brief,'script'=>$script,'asset_name'=>$assetName,'asset_type'=>$assetType,'asset_url'=>$assetUrl]];}
 private function readCsv(string $p):array{$h=fopen($p,'r');$rows=[];while(($x=fgetcsv($h))!==false)$rows[]=$x;fclose($h);return $rows;}
 private function readXlsx(string $p):array{$z=new ZipArchive;abort_unless($z->open($p)===true,422,'Invalid Excel file.');$shared=[];if(($xml=$z->getFromName('xl/sharedStrings.xml'))!==false){$d=simplexml_load_string($xml);foreach($d->si as $si)$shared[]=$this->xmlText($si);}$xml=$z->getFromName('xl/worksheets/sheet1.xml');abort_unless($xml!==false,422,'The first Excel worksheet could not be read.');$s=simplexml_load_string($xml);$s->registerXPathNamespace('x','http://schemas.openxmlformats.org/spreadsheetml/2006/main');$rows=[];foreach($s->xpath('//x:sheetData/x:row') as $row){$vals=[];foreach($row->c as $c){$col=$this->columnIndex((string)$c['r']);$v=(string)$c->v;if((string)$c['t']==='s')$v=$shared[(int)$v]??'';elseif((string)$c['t']==='inlineStr')$v=$this->xmlText($c->is);$vals[$col]=$v;}if($vals){$max=max(array_keys($vals));$rows[(int)$row['r']-1]=array_map(fn($i)=>$vals[$i]??'',range(0,$max));}}$z->close();return $rows;}
 private function xmlText(\SimpleXMLElement $e):string{$e->registerXPathNamespace('x','http://schemas.openxmlformats.org/spreadsheetml/2006/main');return implode('',array_map('strval',$e->xpath('.//x:t')));}
 private function columnIndex(string $ref):int{$letters=preg_replace('/[^A-Z]/i','',$ref);$index=0;foreach(str_split(strtoupper($letters)) as $letter)$index=$index*26+ord($letter)-64;return max(0,$index-1);}
 private function writeXlsx(string $p,array $rows):void{$z=new ZipArchive;$z->open($p,ZipArchive::CREATE|ZipArchive::OVERWRITE);$z->addFromString('[Content_Types].xml','<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>');$z->addFromString('_rels/.rels','<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>');$z->addFromString('xl/workbook.xml','<?xml version="1.0"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Ideas" sheetId="1" r:id="rId1"/></sheets></workbook>');$z->addFromString('xl/_rels/workbook.xml.rels','<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>');$body='';foreach($rows as $ri=>$row){$body.='<row r="'.($ri+1).'">';foreach($row as $ci=>$v)$body.='<c r="'.chr(65+$ci).($ri+1).'" t="inlineStr"><is><t>'.htmlspecialchars($v,ENT_XML1).'</t></is></c>';$body.='</row>';}$z->addFromString('xl/worksheets/sheet1.xml','<?xml version="1.0"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>'.$body.'</sheetData></worksheet>');$z->close();}
}
