<?php
namespace App\Http\Controllers;
use App\Models\{Format,Idea,Pillar};use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Validation\ValidationException;use ZipArchive;
class IdeasImportController extends Controller{
 public function template(Request $r){abort_unless($r->user()->can('ideas.bulk_import'),403);$rows=[['Idea','Pillar','Series','Format'],['Kenapa customer berhenti setelah demo?','Insight / Education','Business 101','Reels']];$tmp=tempnam(sys_get_temp_dir(),'ideas').'.xlsx';$this->writeXlsx($tmp,$rows);return response()->download($tmp,'kolabo-ideas-template.xlsx')->deleteFileAfterSend(true);}
 public function import(Request $r){abort_unless($r->user()->can('ideas.bulk_import'),403);$r->validate(['file'=>'required|file|mimes:xlsx,csv,txt|max:5120']);$rows=strtolower($r->file('file')->getClientOriginalExtension())==='csv'?$this->readCsv($r->file('file')->getRealPath()):$this->readXlsx($r->file('file')->getRealPath());$errors=[];$valid=[];foreach(array_slice($rows,1) as $i=>$row){$line=$i+2;[$idea,$pillarName,$seriesName,$formatName]=array_pad($row,4,'');$pillar=Pillar::where('name',trim($pillarName))->where('is_active',true)->first();$series=$pillar?->series()->where('name',trim($seriesName))->where('is_active',true)->first();$format=Format::where('name',trim($formatName))->where('is_active',true)->first();if(!trim($idea))$errors[]="Row $line: Idea is required";if(!$pillar)$errors[]="Row $line: Pillar \"$pillarName\" is invalid";elseif(!$series)$errors[]="Row $line: Series \"$seriesName\" does not belong to Pillar \"$pillarName\"";if(!$format)$errors[]="Row $line: Format \"$formatName\" is required or invalid";if($pillar&&$series&&$format&&trim($idea))$valid[]=['idea'=>strip_tags($idea,'<b><strong><i><em><u><br><p>'),'pillar_id'=>$pillar->id,'series_id'=>$series->id,'format_id'=>$format->id];}if($errors)throw ValidationException::withMessages(['file'=>implode(' | ',$errors)]);DB::transaction(fn()=>collect($valid)->each(fn($d)=>Idea::create($d+['submitted_by'=>$r->user()->id,'source_department_id'=>$r->user()->department_id,'status'=>'new'])));return back()->with('success',count($valid).' ideas imported successfully.');}
 private function readCsv(string $p):array{$h=fopen($p,'r');$rows=[];while(($x=fgetcsv($h))!==false)$rows[]=$x;fclose($h);return $rows;}
 private function readXlsx(string $p):array{$z=new ZipArchive;abort_unless($z->open($p)===true,422,'Invalid Excel file.');$shared=[];if(($xml=$z->getFromName('xl/sharedStrings.xml'))!==false){$d=simplexml_load_string($xml);foreach($d->si as $si)$shared[]=implode('',array_map('strval',$si->xpath('.//t')));}$s=simplexml_load_string($z->getFromName('xl/worksheets/sheet1.xml'));$s->registerXPathNamespace('x','http://schemas.openxmlformats.org/spreadsheetml/2006/main');$rows=[];foreach($s->xpath('//x:sheetData/x:row') as $row){$vals=[];foreach($row->c as $c){$col=ord(preg_replace('/\d/','',(string)$c['r']))-65;$v=(string)$c->v;if((string)$c['t']==='s')$v=$shared[(int)$v]??'';elseif((string)$c['t']==='inlineStr')$v=(string)$c->is->t;while(count($vals)<$col)$vals[]='';$vals[]=$v;}$rows[]=$vals;}$z->close();return $rows;}
 private function writeXlsx(string $p,array $rows):void{$z=new ZipArchive;$z->open($p,ZipArchive::CREATE|ZipArchive::OVERWRITE);$z->addFromString('[Content_Types].xml','<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>');$z->addFromString('_rels/.rels','<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>');$z->addFromString('xl/workbook.xml','<?xml version="1.0"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Ideas" sheetId="1" r:id="rId1"/></sheets></workbook>');$z->addFromString('xl/_rels/workbook.xml.rels','<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>');$body='';foreach($rows as $ri=>$row){$body.='<row r="'.($ri+1).'">';foreach($row as $ci=>$v)$body.='<c r="'.chr(65+$ci).($ri+1).'" t="inlineStr"><is><t>'.htmlspecialchars($v,ENT_XML1).'</t></is></c>';$body.='</row>';}$z->addFromString('xl/worksheets/sheet1.xml','<?xml version="1.0"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>'.$body.'</sheetData></worksheet>');$z->close();}
}
