<?php
namespace App\Http\Controllers;
use App\Enums\{ContentStatus,IdeaStatus};use App\Models\{Account,Asset,Content,ContentBrief,Department,Format,Idea,Pillar,Platform,Series,User};use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Validation\Rule;use Spatie\Permission\Models\Role;
class KolaboController extends Controller {
 private function refs():array{return ['pillars'=>Pillar::with('series')->get(),'accounts'=>Account::all(),'platforms'=>Platform::all(),'formats'=>Format::all(),'users'=>User::where('is_active',true)->get()];}
 public function dashboard(Request $r){abort_unless($r->user()->can('dashboard.view'),403);$q=Content::query();$stats=['Total Content'=>(clone$q)->count(),'In Production'=>(clone$q)->where('status','in_production')->count(),'Review'=>(clone$q)->where('status','review')->count(),'Scheduled'=>(clone$q)->where('status','scheduled')->count(),'Published'=>(clone$q)->where('status','published')->count()];return view('dashboard',compact('stats')+['today'=>Content::with(['platforms','pic'])->whereDate('publish_date',today())->get(),'upcoming'=>Content::with('pic')->whereBetween('publish_date',[today(),today()->addDays(7)])->orderBy('publish_date')->get(),'byPillar'=>Content::select('pillar_id',DB::raw('count(*) total'))->with('pillar')->groupBy('pillar_id')->get(),'byPlatform'=>Platform::withCount('contents')->get()]);}
 public function contents(Request $r){abort_unless($r->user()->can('content.view'),403);$q=Content::with(['account','platforms','pillar','series','format','pic']);if($r->filled('search'))$q->where('title','like','%'.$r->search.'%');foreach(['account_id','pillar_id','series_id','pic_user_id','status'] as $f)if($r->filled($f))$q->where($f,$r->$f);return view('content.index',$this->refs()+['contents'=>$q->latest('publish_date')->paginate(12)->withQueryString()]);}
 public function storeContent(Request $r){abort_unless($r->user()->can('content.create'),403);$d=$this->contentData($r);$d['status']='planned';$c=Content::create($d+['created_by'=>$r->user()->id,'updated_by'=>$r->user()->id]);$c->platforms()->sync($r->input('platform_ids',[]));ContentBrief::create(['content_id'=>$c->id]);return redirect()->route('content.show',$c)->with('success','Content berhasil dibuat.');}
 public function showContent(Request $r,Content $content){abort_unless($r->user()->can('content.view'),403);return view('content.show',$this->refs()+['content'=>$content->load(['account','platforms','pillar','series','format','pic','sourceIdea.submitter.department','brief','assets.addedBy','revisions.author','comments.user']),'activities'=>$content->activities()->latest()->get()]);}
 private function contentData(Request $r):array{$d=$r->validate(['title'=>'required|max:255','publish_date'=>'nullable|date','account_id'=>'nullable|exists:accounts,id','pillar_id'=>'required|exists:pillars,id','series_id'=>['required',Rule::exists('series','id')->where(fn($q)=>$q->where('pillar_id',$r->pillar_id))],'format_id'=>'nullable|exists:formats,id','pic_user_id'=>['nullable',Rule::exists('users','id')->where('is_active',true)],'status'=>['required',Rule::enum(ContentStatus::class)],'final_url'=>'nullable|url','platform_ids'=>'array','platform_ids.*'=>'exists:platforms,id']);unset($d['platform_ids']);return $d;}
 public function ideas(Request $r){$u=$r->user();abort_unless($u->can('ideas.view_all')||$u->can('ideas.view_own'),403);$q=Idea::with(['pillar','series','submitter','department']);if(!$u->can('ideas.view_all'))$q->where('submitted_by',$u->id);return view('ideas.index',$this->refs()+['ideas'=>$q->latest()->paginate(15)]);}
 public function storeIdea(Request $r){abort_unless($r->user()->can('ideas.create'),403);$d=$r->validate(['idea'=>'required|max:5000','pillar_id'=>'required|exists:pillars,id','series_id'=>['required',Rule::exists('series','id')->where(fn($q)=>$q->where('pillar_id',$r->pillar_id))],'format_id'=>'nullable|exists:formats,id']);$d['idea']=strip_tags($d['idea'],'<b><strong><i><em><u><br><p>');$idea=Idea::create($d+['submitted_by'=>$r->user()->id,'source_department_id'=>$r->user()->department_id,'status'=>'new']);activity()->causedBy($r->user())->performedOn($idea)->log('submitted an idea');return back()->with('success','Idea berhasil dikirim.');}
 public function ideaStatus(Request $r,Idea $idea){abort_unless($r->user()->can('ideas.select'),403);$d=$r->validate(['status'=>['required',Rule::enum(IdeaStatus::class)]]);$idea->update($d);return back()->with('success','Status idea diperbarui.');}
 public function moveIdea(Request $r,Idea $idea){abort_unless($r->user()->can('ideas.move_to_content'),403);abort_unless($idea->status===IdeaStatus::Selected,422,'Idea harus Selected.');$r->merge(['status'=>'planned','format_id'=>$r->input('format_id',$idea->format_id)]);$data=$this->contentData($r);DB::transaction(function()use($idea,$data,$r){$c=Content::create($data+['source_idea_id'=>$idea->id,'created_by'=>$r->user()->id,'updated_by'=>$r->user()->id]);$c->platforms()->sync($r->input('platform_ids',[]));ContentBrief::create(['content_id'=>$c->id]);$idea->update(['status'=>'converted']);activity()->causedBy($r->user())->performedOn($c)->log('converted idea to content');});return redirect()->route('content.index')->with('success','Idea dikonversi ke Content Plan.');}
 public function calendar(Request $r){abort_unless($r->user()->can('calendar.view'),403);$colors=['Product'=>'#3b82f6','News'=>'#ec4899','Insight / Education'=>'#f59e0b','Entertainment'=>'#f97316','Community'=>'#8b5cf6','Brand'=>'#06b6d4'];$calendarEvents=Content::with(['platforms','pillar'])->whereNotNull('publish_date')->get()->map(fn(Content $content)=>['id'=>$content->id,'title'=>$content->title,'start'=>$content->publish_date->format('Y-m-d'),'url'=>route('content.show',$content),'backgroundColor'=>$content->status===ContentStatus::Published?'#16a34a':($colors[$content->pillar->name]??'#64748b'),'classNames'=>['status-'.$content->status->value],'extendedProps'=>['platforms'=>$content->platforms->pluck('name')->values()->all(),'status'=>$content->status->value]])->values();return view('calendar',compact('calendarEvents'));}
 public function updateDate(Request $r,Content $content){abort_unless($r->user()->can('calendar.edit'),403);$content->update(['publish_date'=>$r->validate(['publish_date'=>'required|date'])['publish_date'],'updated_by'=>$r->user()->id]);return response()->json(['ok'=>true]);}
 public function production(Request $r){abort_unless($r->user()->can('production.view'),403);return view('production',['groups'=>Content::with(['series','platforms','pic'])->get()->groupBy(fn($c)=>$c->status->value)]);}
 public function updateStatus(Request $r,Content $content){abort_unless($r->user()->can('production.change_status')||$r->user()->can('content.change_status'),403);$d=$r->validate(['status'=>['required',Rule::enum(ContentStatus::class)]]);$target=ContentStatus::from($d['status']);$rollback=$r->user()->hasAnyRole(['Super Admin','Creative Lead']);abort_unless($content->status->canTransitionTo($target,$rollback),422,'This status transition is not allowed.');$old=$content->status->label();$content->update(['status'=>$target,'updated_by'=>$r->user()->id]);activity()->causedBy($r->user())->performedOn($content)->withProperties(['old'=>$old,'new'=>$target->label()])->log('changed content status');return response()->json(['ok'=>true,'message'=>'Status updated successfully']);}
 public function published(Request $r){abort_unless($r->user()->can('published.view'),403);return view('published',['contents'=>Content::with(['account','platforms','pillar','series','pic'])->where('status','published')->latest('publish_date')->paginate(12)]);}
 public function myTasks(Request $r){$items=Content::with(['platforms','pic'])->where('pic_user_id',$r->user()->id)->where('status','!=','published')->orderBy('publish_date')->get();return view('my-tasks',['groups'=>['Overdue'=>$items->filter(fn($x)=>$x->publish_date?->isPast()&&!$x->publish_date->isToday()),'Today'=>$items->filter(fn($x)=>$x->publish_date?->isToday()),'This Week'=>$items->filter(fn($x)=>$x->publish_date?->between(today()->addDay(),today()->endOfWeek())),'Upcoming'=>$items->filter(fn($x)=>$x->publish_date?->gt(today()->endOfWeek()))]]);}
 public function team(Request $r){abort_unless($r->user()->can('team.view'),403);return view('team',['users'=>User::role(['Creative Lead','Creative Member'])->withCount(['assignedContents as assigned_count','assignedContents as progress_count'=>fn($q)=>$q->where('status','in_production'),'assignedContents as review_count'=>fn($q)=>$q->where('status','review'),'assignedContents as scheduled_count'=>fn($q)=>$q->where('status','scheduled')])->get()]);}
 public function assets(Request $r){abort_unless($r->user()->can('assets.view'),403);return view('assets',['assets'=>Asset::with('addedBy')->latest()->paginate(15)]);}
 public function storeAsset(Request $r){abort_unless($r->user()->can('assets.create'),403);Asset::create($r->validate(['title'=>'required','category'=>'required','asset_type'=>'nullable','url'=>'required|url'])+['added_by'=>$r->user()->id]);return back()->with('success','Asset ditambahkan.');}
 public function users(Request $r){abort_unless($r->user()->can('users.view'),403);return view('admin.users',['users'=>User::with(['department','roles'])->paginate(20),'departments'=>Department::all(),'roles'=>Role::all()]);}
 public function storeUser(Request $r){abort_unless($r->user()->can('users.create'),403);$d=$r->validate(['name'=>'required','email'=>'required|email|unique:users','password'=>'required|min:8','department_id'=>'required|exists:departments,id','role'=>'required|exists:roles,name']);$u=User::create($d);$u->syncRoles($d['role']);return back()->with('success','User dibuat.');}
 public function toggleUser(Request $r,User $user){abort_unless($r->user()->can('users.deactivate'),403);abort_if($user->id===$r->user()->id,422);$user->update(['is_active'=>!$user->is_active]);return back()->with('success','Status user diperbarui.');}
 public function roles(Request $r){abort_unless($r->user()->can('roles.view'),403);return view('admin.roles',['roles'=>Role::with('permissions')->get()]);}
}
