<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><link rel="icon" href="{{ asset('favicon.svg') }}" type="image/svg+xml"><title>{{ $title ?? 'Kolabo Creative' }}</title>@vite(['resources/css/app.css','resources/js/app.js'])<script defer src="{{ asset('vendor/alpinejs/cdn.min.js') }}"></script><style>[x-cloak]{display:none}[data-testid="edit-content-modal"] form{max-height:90vh;overflow-y:auto}</style></head>
<body x-data="{menu:false}" class="antialiased">
@php($nav=[['OVERVIEW',[['dashboard','Dashboard','dashboard.view'],['sales-dashboard','Request Dashboard','sales_dashboard.view']]],['CONTENT',[['ideas.index','Ideas','ideas.create'],['content.index','Content Plan','content.view'],['production','Production','production.view'],['calendar','Calendar','calendar.view']]],['LIBRARY',[['published','Published','published.view'],['assets','Assets','assets.view']]],['TEAM',[['my-tasks','My Tasks',null],['team','Team','team.view']]],['ADMINISTRATION',[['users','Users','users.view'],['roles','Roles & Permissions','roles.view'],['accounts','Accounts','accounts.view'],['masters','Pillars & Series','pillars.view']]]])
<div class="min-h-screen lg:flex"><div x-cloak x-show="menu" @click="menu=false" class="fixed inset-0 z-30 bg-slate-950/25 lg:hidden"></div>
<aside :class="menu?'translate-x-0':'-translate-x-full lg:translate-x-0'" class="app-sidebar fixed lg:sticky top-0 z-40 flex h-screen w-[224px] shrink-0 flex-col transition-transform duration-200"><div class="flex h-[68px] items-center px-5"><x-app-logo /></div>
<nav class="sidebar-scroll flex-1 px-3 pb-3">@foreach($nav as [$group,$links])<div class="nav-group">{{ $group }}</div>@foreach($links as [$route,$label,$permission])@if(!$permission||auth()->user()->can($permission))<a class="nav {{ request()->routeIs($route)?'active':'' }}" href="{{ route($route) }}"><span class="nav-icon"><x-sidebar-icon :name="$route" /></span><span>{{ $label }}</span></a>@endif @endforeach @endforeach</nav>
<div class="p-3 pt-1"><div class="user-card flex items-center gap-3 p-3"><div class="avatar h-9 w-9 shrink-0">{{ strtoupper(substr(auth()->user()->name,0,1)) }}</div><div class="min-w-0 flex-1"><b class="block truncate text-xs">{{ auth()->user()->name }}</b><span class="block truncate text-[10px] text-slate-500">{{ auth()->user()->roles->first()?->name }}</span></div><form method="post" action="{{ route('logout') }}">@csrf<button aria-label="Logout" title="Logout" class="rounded-md p-1.5 text-slate-400 hover:bg-red-50 hover:text-red-500"><svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M10 17l5-5-5-5M15 12H3M14 3h5a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-5"/></svg></button></form></div></div></aside>
<main class="min-w-0 flex-1"><header class="app-topbar sticky top-0 z-20 flex items-center justify-between px-4 lg:px-7"><div class="flex items-center gap-3"><button aria-label="Open navigation" class="rounded-lg border border-slate-200 p-2 text-[#34547f] lg:hidden" @click="menu=!menu"><svg aria-hidden="true" class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"><path d="M4 7h16M4 12h16M4 17h16"/></svg></button><span class="text-[11px] font-medium text-[#536989]">Kolabo Creative Workspace</span></div><div class="flex items-center gap-3"><span class="hidden text-xs text-slate-500 sm:block">{{ now()->format('D, d M Y') }}</span><div class="avatar h-8 w-8 text-xs">{{ strtoupper(substr(auth()->user()->name,0,1)) }}</div></div></header>
<div class="p-4 sm:p-5 lg:p-7 xl:p-8">@if(session('success'))<div data-testid="success" class="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{{ session('success') }}</div>@endif @if($errors->any())<div data-testid="error" class="mb-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{{ $errors->first() }}</div>@endif @yield('content')</div></main></div>@stack('scripts')</body></html>
